version: '3.9'
name: 'auht_ms'

services:
  sibu_auth_db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: auth_db
    ports:
      - 5432:5432
    volumes:
      - auth_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: juan@unal.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  sibu_auth_ms:
    image: sibu_auth_ms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - sibu_auth_db
    environment:
      PORT: 3000
      POSTGRES_HOST: sibu_auth_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      JWT_SECRET: secret

volumes:
  auth_data:
  pgadmin-data:
